### PR TITLE
chaos: fix typo "print_"

### PR DESCRIPTION
**Pull request by bennn**
amazingly this was not a type error in retic

### CODE REVIEW

**Comment by bennn** [comment]
@mhyee  can I have write access?

**Comment by mhyee** [comment]
I don't think I'm able to do that, maybe @camoy?

(I'm also not sure if this is a repo or organization permissions thing.)

**Comment by camoy** [comment]
No idea why you lost write access given that you're still in the nuprl org, but you should have admin access to this repo now.

**Comment by bennn** [comment]
thanks!!!

**Pull request merged**
